In [2]:
import glob
import os
import torch
import warnings

import torch.multiprocessing
import torch.nn.functional as F

In [3]:
os.chdir('genre_classification_289a/src')

In [4]:
torch.multiprocessing.set_sharing_strategy('file_system')

warnings.filterwarnings("ignore")

import numpy as np

from multiprocessing import cpu_count
import fma_utils as utils

audio_dir = '../data/fma_xsmall' #path to audio files
target_dir = os.path.join(audio_dir, 'targets') #path to extracted spectograms and targets  (stored in npz)

In [5]:
tracks = utils.load('../data/fma_metadata/tracks.csv') #load tracks df
genres = utils.load('../data/fma_metadata/genres.csv') #load genres df

In [6]:
target_paths = [*glob.iglob(os.path.join(target_dir, '*_targets.npz'), recursive=True)] #list paths to targets
tids = list(map(lambda x: int(os.path.splitext(os.path.basename(x).replace('_targets', ''))[0]), target_paths)) #list of track ids

In [7]:
data_0 = np.load(target_paths[0])

In [8]:
data_0['subgenres']

array([0.025   , 0.025   , 0.025   , 0.025   , 0.025   , 6.024996,
       0.025   , 0.025   , 0.025   , 0.025   , 0.025   , 0.025   ,
       0.025   , 0.025   , 0.025   , 0.025   , 0.025   , 0.025   ,
       0.025   , 0.025   , 0.025   , 0.025   , 0.025   , 0.025   ,
       0.025   , 0.025   , 0.025   , 0.025   , 0.025   , 0.025   ,
       0.025   , 0.025   , 0.025   , 0.025   , 0.025   , 0.025   ,
       0.025   , 0.025   , 0.025   , 0.025   ], dtype=float32)

In [9]:
np_ver = data_0['subgenres']

In [10]:
t_ver = torch.from_numpy(np_ver)

In [11]:
t_ver.max()

tensor(6.0250)

In [12]:
vec = np.zeros_like(np_ver)

In [13]:
vec[np_ver.argmax()] = 1

In [14]:
torch.from_numpy(vec)

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [15]:
np.where(np_ver == np_ver.max())

(array([5]),)

In [16]:
(np_ver == np_ver.max())*1

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
torch.cuda.is_available()

True

In [19]:
t_ver.cuda()

tensor([0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 6.0250, 0.0250, 0.0250, 0.0250,
        0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250,
        0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250,
        0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250, 0.0250,
        0.0250, 0.0250, 0.0250, 0.0250], device='cuda:0')